pizza/food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns =[
    path('pizza', views.pizza, name='pizza'),
    path('rolls', views.rolls, name='rolls'),
    path('drinks', views.drinks, name='drinks'),
    path('order', views.order, name='order'),
    path('success', views.success, name='success'),
]

pizza/pizza/urls.py
from django.contrib import admin
from django.urls import include, path
from food import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('food/', include('food.urls'))
]

pizza/food/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.DecimalField(max_digits=4, decimal_places=2)
    priceL = models.DecimalField(max_digits=4, decimal_places=2)
    pImage = models.URLField()


class Roll(models.Model):
    name = models.CharField(max_length=120)
    price5 = models.DecimalField(max_digits=4, decimal_places=2)
    price10 = models.DecimalField(max_digits=4, decimal_places=2)
    rImage = models.URLField()


class Drink(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.DecimalField(max_digits=4, decimal_places=2)
    priceL = models.DecimalField(max_digits=4, decimal_places=2)
    dImage = models.URLField()

pizza/food/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt

from .models import Pizza, Drink, Roll


# Create your views here.
def index(request):
    request.session.set_expiry(0)
    ctx = {'active_link': 'index'}
    return render(request, 'food/index.html', ctx)


def pizza(request):
    request.session.set_expiry(0)
    pizzas = Pizza.objects.all()
    ctx = {'pizzas': pizzas,
           'active_link': 'pizza'}
    return render(request, 'food/pizza.html', ctx)


def rolls(request):
    request.session.set_expiry(0)
    rolls = Roll.objects.all()
    ctx = {'rolls': rolls,
           'active_link': 'rolls'}
    return render(request, 'food/rolls.html', ctx)


def drinks(request):
    request.session.set_expiry(0)
    drinks = Drink.objects.all()
    ctx = {'drinks': drinks,
           'active_link': 'drinks'}
    return render(request, 'food/drinks.html', ctx)


@csrf_exempt
def order(request):
    request.session.set_expiry(0)
    if request.method == 'POST' and request.is_ajax():
        request.session['note'] = request.POST.get('note')
        request.session['order'] = request.POST.get('orders')
        return JsonResponse({'success': True})
    ctx = {'active_link': 'order'}
    return render(request, 'food/order.html', ctx)


def success(request):
    return render(request, 'food/success.html')

pizza/food/templates/food/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="https://img.icons8.com/cotton/40/000000/pizza.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'food/css/style.css' %}" >
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="{% url 'index' %}">
        <img src="https://img.icons8.com/cotton/40/000000/pizza.png" class="logo"/>
    </a>
        <button class="navbar-toggler" type="button" data-toggler="collapse" data-target="#mynav" aria-controls="mynav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse" id="mynav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link {% if active_link == 'index' %}active{% endif %}" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if active_link == 'pizza' %}active{% endif %}" href="{% url 'food:pizza' %}">Pizzas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if active_link == 'rolls' %}active{% endif %}" href="{% url 'food:rolls' %}">Rolls</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if active_link == 'drinks' %}active{% endif %}" href="{% url 'food:drinks' %}">Drinks</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mt-2">
                <a href="{% url 'food:order' %}" class="nav-link {% if active_link == 'drinks' %}active{% endif %}"><img src="https://img.icons8.com/fluent/30/000000/shopping-cart.png"/><span id="cart"></span></a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link"><img class="bg-light ml-2 rounded circle" src="https://img.icons8.com/windows/24/000000/user.png"/><br>Login</a>
            </li>
        </ul>
        </div>
    </nav>
    <div>
      {% block content %}{% endblock %}
    </div>

<!-- jQuery library -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'food/js/main.js' %}"></script>

</body>
</html>

pizza/food/templates/food/drinks.html
{% extends 'food/base.html' %}

{% block title %} Drinks {% endblock %}

{% block content %}
    <div class="container-fluid">
    <div class="row text-center">
        <div class="col-md-8">
            <h2 class="title">Our Drinks</h2>
            <div class="row">
                {% for drink in drinks %}
                <div class="col-md-6 p-4">
                    <img class="picture" src="{{ drink.dImage }}">
                    <h4 class="pt-3">{{ drink.name }}</h4>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-inline" type="radio" checked>
                            {{ drink.priceM }} $
                        </label>
                    </div>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-inline" type="radio" checked>
                            {{ drink.priceL }} $
                        </label>
                    </div>
                    <div>
                        <button class="btn-info pt-3">Add to cart</button>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
        <div class="col-md-4">

        </div>
    </div>
</div>
{% endblock %}

pizza/food/templates/food/index.html
{% extends 'food/base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
    <div class="home"></div>
{% endblock %}

pizza/food/templates/food/order.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %} Order {% endblock %}


{% block content %}

    <div class="container-fluid m-4 ">
        <div class="row">
            <div class="col-md-7 text-center">
                <h2> Order </h2>
                <div class="row">
                    <div class="col-md-3" id="name">
                        <h3> Name </h3>
                    </div>
                    <div class="col-md-3" id="size">
                        <h3> Size </h3>
                    </div>
                    <div class="col-md-3" id="price">
                        <h3> Price </h3>
                    </div>
                    <div class="col-md-1" id="rm">

                    </div>
                </div>
                <h2 id="total">Total:</h2>
            </div>
            <div class="col-md-5 mt-4">
                <h2 class="mb-4"> Message:</h2>
                <textarea name="message" id="message" cols="40" rows="5"></textarea>
                <div class="ml-auto m-4">
                    <button type="submit" class="btn-success" onclick="order()"> Submit </button>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'food/js/cart.js' %}"></script>
{% endblock %}

pizza/food/templates/food/pizza.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %} Pizza {% endblock %}


{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 text-center">
            <h2 class="title">Our Pizzas</h2>
            <div class="row">
                {% for pizza in pizzas %}
                <div class="col-md-6 p-4">
                    <img class="picture" src="{{ pizza.pImage }}">
                    <h4 class="pt-3" id="piz{{ pizza.id }}">{{ pizza.name }}</h4>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-inline" type="radio" name="pizza{{ pizza.id }}" value="{{ pizza.priceM }}" checked>
                            M:{{ pizza.priceM }} $
                        </label>
                    </div>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-inline" name="pizza{{ pizza.id }}" type="radio" value="{{ pizza.priceL }}">
                            L:{{ pizza.priceL }} $
                        </label>
                    </div>
                    <div>
                        <button class="btn-info mt-3" onclick="addPizza('{{ pizza.id }}')">Add to cart</button>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
        <div class="col-md-4 orders">
            <div class="bg-dark p-4 rounded text-light">
                <h2 class="text-center">Order list</h2>
                <ul id="pcart"></ul>
                <h4 class="text-right" id="ptotal">Total: 0$</h4>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'food/js/order.js' %}"></script>
{% endblock %}

pizza/food/templates/food/rolls.html
{% extends 'food/base.html' %}

{% block title %} Rolls {% endblock %}

{% block content %}
    <div class="container-fluid">
    <div class="row text-center">
        <div class="col-md-8">
            <h2 class="title">Our Rolls</h2>
            <div class="row">
                {% for roll in rolls %}
                <div class="col-md-6 p-4">
                    <img class="picture" src="{{ roll.rImage }}">
                    <h4 class="pt-3">{{ roll.name }}</h4>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-inline" type="radio" checked>
                            {{ roll.price5 }} $
                        </label>
                    </div>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-inline" type="radio" checked>
                            {{ roll.price10 }} $
                        </label>
                    </div>
                    <div>
                        <button class="btn-info pt-3">Add to cart</button>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
        <div class="col-md-4">

        </div>
    </div>
</div>
{% endblock %}

pizza/food/templates/food/success.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %} Success {% endblock %}


{% block content %}
    <div>
        <h2>
            We have recived your order
        </h2>
    </div>
{% endblock %}